class Category:
    BILL = "BILL"
    SUBSCRIPTION = "SUBSCRIPTION"
    GROCERY = "GROCERY"
    GAS = "GAS"
    WORK_MEAL = "WORK MEAL"
    RESTAURANT = "RESTAURANT"
    CLOTHES = "CLOTHES"
    CAR = "CAR"
    NECESSITY = "NECESSITY"
    PLEASURE = "PLEASURE"
    RANDOM = "RANDOM"


