class Category:
    BILLS = "BILLS"
    GROCERIES_MEALS = "GROCERIES/MEALS"
    NECESSITIES = "NECESSITIES"
    PLEASURE = "PLEASURE"
    QOL = "QOL"  # Quality of Life
    SUBSCRIPTIONS = "SUBSCRIPTIONS"
